export const REQUEST_EXAMPLE_INSTANCES = 'REQUEST_EXAMPLE_INSTANCES';
export const RECEIVE_EXAMPLE_INSTANCES = 'RECEIVE_EXAMPLE_INSTANCES';
export const RECEIVE_EXAMPLE_INSTANCES_ERROR = 'RECEIVE_EXAMPLE_INSTANCES_ERROR';